import asyncio
from logging.config import fileConfig
from typing import Any

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config
from sqlalchemy.sql.schema import SchemaItem

from alembic import context
from app.config import get_settings
from app.db import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# The URL lives in the environment (see `.env.example`), never in alembic.ini.
config.set_main_option("sqlalchemy.url", get_settings().database_url)

target_metadata = Base.metadata

# Supabase owns `auth`, `storage`, `realtime`, etc. in the same database.
# Without this filter, autogenerate reflects them and emits DROP TABLE for
# every one of them. Only `public` is ours.
INCLUDED_SCHEMAS = {"public", None}


def include_name(name: str | None, type_: str, parent_names: dict[str, str | None]) -> bool:
    if type_ == "schema":
        return name in INCLUDED_SCHEMAS
    return True


# The `geog` columns and their spatial index are written by hand in the initial
# migration and must never be autogenerated. Two independent reasons:
#
# 1. geoalchemy2 renders the type unqualified -- `geography(Point,4326)` -- which
#    cannot resolve under the `search_path = public` pinned below, because Supabase
#    installs PostGIS into `extensions`.
# 2. Alembic does not compare `Computed()` expressions, so it can neither generate
#    the generated-column body correctly nor detect drift in it afterwards.
#
# Without this filter, every autogenerate run proposes dropping and re-adding both
# columns and the index. See app/db/models.py.
HAND_WRITTEN_COLUMNS = {("gyms", "geog"), ("saved_locations", "geog")}
HAND_WRITTEN_INDEXES = {"gyms_geog_idx"}
# `profiles.id -> auth.users(id)` exists in the database but cannot exist on the
# model: autogenerate is restricted to `public` and cannot see `auth`, and declaring
# it would force a stub `auth.users` Table into the metadata. The reflected FK
# therefore looks like one we deleted, and every autogenerate run proposes dropping
# it -- which would sever profiles from Supabase Auth. Verified against the real
# database: without this entry the next revision emits
# `op.drop_constraint('profiles_id_fkey', 'profiles', type_='foreignkey')`.
HAND_WRITTEN_FOREIGN_KEYS = {"profiles_id_fkey"}


def include_object(
    obj: SchemaItem, name: str | None, type_: str, reflected: bool, compare_to: Any
) -> bool:
    if type_ == "column":
        return (obj.table.name, name) not in HAND_WRITTEN_COLUMNS  # type: ignore[attr-defined]
    if type_ == "index":
        return name not in HAND_WRITTEN_INDEXES
    if type_ == "foreign_key_constraint":
        return name not in HAND_WRITTEN_FOREIGN_KEYS
    return True


def run_migrations_offline() -> None:
    """Run migrations without a DBAPI connection, emitting SQL to stdout."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_schemas=False,
        include_name=include_name,
        include_object=include_object,
        compare_type=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    # Supabase installs extensions into `extensions` and puts that schema on the
    # postgres role's search_path. Reflection then sees PostGIS's own objects
    # (spatial_ref_sys, geometry_columns) as unqualified — i.e. as if they were
    # ours — and autogenerate emits DROP TABLE for them. Verified against the
    # real project: without this line, the first autogenerate drops spatial_ref_sys
    # and takes every coordinate transform with it.
    #
    # `include_name` cannot catch this: these objects report schema None, not
    # "extensions". Pinning the search_path is what actually scopes reflection.
    connection.exec_driver_sql("SET search_path TO public")

    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_schemas=False,
        include_name=include_name,
        include_object=include_object,
        compare_type=True,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    connectable = async_engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)
        # REQUIRED -- do not remove. `do_run_migrations` issues `SET search_path`
        # before configuring Alembic, which leaves the connection inside a
        # transaction. Alembic detects that (`MigrationContext._in_external
        # _transaction`) and deliberately makes its own `begin_transaction()` a
        # no-op, handing commit responsibility to this function. Without this
        # line `connect()` rolls back on close and the migration is silently
        # discarded: it logs "Running upgrade ..." and changes nothing at all.
        await connection.commit()

    await connectable.dispose()


def run_migrations_online() -> None:
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
