"""create core schema

Reproduces boulder_bay_schema.sql Part 1. Everything below the
"hand-written" marker in upgrade() is something autogenerate cannot
emit; see the comments there and app/db/models.py.

Revision ID: 7bea7599f868
Revises:
Create Date: 2026-09-08 16:22:01.744041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bea7599f868'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Every application table, for the RLS block at the end of upgrade().
TABLES = (
    'profiles',
    'gyms',
    'gym_hours',
    'busyness_snapshots',
    'busyness_curves',
    'gym_memberships',
    'saved_locations',
    'ranking_prefs',
    'travel_times',
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gyms',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('brand', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('timezone', sa.Text(), server_default=sa.text("'America/Los_Angeles'"), nullable=False),
    sa.Column('google_maps_query', sa.Text(), nullable=False),
    sa.Column('google_maps_url', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('waiver_url', sa.Text(), nullable=True),
    sa.Column('day_pass_cents', sa.Integer(), nullable=True),
    sa.Column('day_pass_peak_cents', sa.Integer(), nullable=True),
    sa.Column('peak_starts_at', sa.Time(), nullable=True),
    sa.Column('monthly_cents', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("brand in ('movement', 'touchstone', 'benchmark', 'independent')", name='gyms_brand_valid'),
    sa.CheckConstraint("slug ~ '^[a-z0-9-]+$'", name='gyms_slug_format'),
    sa.CheckConstraint('day_pass_cents >= 0', name='gyms_day_pass_nonneg'),
    sa.CheckConstraint('day_pass_peak_cents >= 0', name='gyms_peak_pass_nonneg'),
    sa.CheckConstraint('latitude between -90 and 90', name='gyms_latitude_range'),
    sa.CheckConstraint('longitude between -180 and 180', name='gyms_longitude_range'),
    sa.CheckConstraint('monthly_cents >= 0', name='gyms_monthly_nonneg'),
    sa.CheckConstraint('num_nulls(day_pass_peak_cents, peak_starts_at) <> 1', name='gyms_peak_rate_complete'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('busyness_curves',
    sa.Column('gym_id', sa.BigInteger(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('hour_of_day', sa.SmallInteger(), nullable=False),
    sa.Column('busy_pct', sa.SmallInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('busy_pct between 0 and 100', name='busyness_curves_pct_range'),
    sa.CheckConstraint('day_of_week between 0 and 6', name='busyness_curves_day_range'),
    sa.CheckConstraint('hour_of_day between 0 and 23', name='busyness_curves_hour_range'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gym_id', 'day_of_week', 'hour_of_day')
    )
    op.create_table('busyness_snapshots',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('gym_id', sa.BigInteger(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('live_pct', sa.SmallInteger(), nullable=True),
    sa.Column('typical_pct', sa.SmallInteger(), nullable=True),
    sa.Column('source', sa.Text(), server_default=sa.text("'google_maps'"), nullable=False),
    sa.CheckConstraint('live_pct between 0 and 100', name='busyness_snapshots_live_range'),
    sa.CheckConstraint('typical_pct between 0 and 100', name='busyness_snapshots_typical_range'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gym_id', 'observed_at', name='busyness_snapshots_tick_unique')
    )
    op.create_table('gym_hours',
    sa.Column('gym_id', sa.BigInteger(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=False),
    sa.Column('closes_at', sa.Time(), nullable=False),
    sa.CheckConstraint('closes_at > opens_at', name='gym_hours_ordered'),
    sa.CheckConstraint('day_of_week between 0 and 6', name='gym_hours_day_range'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('gym_id', 'day_of_week')
    )
    op.create_table('gym_memberships',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'gym_id')
    )
    op.create_table('ranking_prefs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('w_crowd', sa.Numeric(precision=5, scale=3), server_default=sa.text('0.6'), nullable=False),
    sa.Column('w_travel', sa.Numeric(precision=5, scale=3), server_default=sa.text('0.5'), nullable=False),
    sa.Column('member_boost', sa.Numeric(precision=5, scale=2), server_default=sa.text('15'), nullable=False),
    sa.Column('closed_penalty', sa.Numeric(precision=5, scale=2), server_default=sa.text('60'), nullable=False),
    sa.Column('travel_cap_minutes', sa.SmallInteger(), server_default=sa.text('60'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('travel_cap_minutes > 0', name='ranking_prefs_travel_cap_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('saved_locations',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Double(), nullable=False),
    sa.Column('longitude', sa.Double(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('latitude between -90 and 90', name='saved_locations_latitude_range'),
    sa.CheckConstraint('longitude between -180 and 180', name='saved_locations_longitude_range'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'label', name='saved_locations_label_unique')
    )
    op.create_index('saved_locations_one_default_idx', 'saved_locations', ['user_id'], unique=True, postgresql_where=sa.text('is_default'))
    op.create_index('saved_locations_user_idx', 'saved_locations', ['user_id'], unique=False)
    op.create_table('travel_times',
    sa.Column('location_id', sa.Uuid(), nullable=False),
    sa.Column('gym_id', sa.BigInteger(), nullable=False),
    sa.Column('minutes', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('meters', sa.Integer(), nullable=True),
    sa.Column('provider', sa.Text(), server_default=sa.text("'mapbox'"), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider in ('mapbox', 'haversine_fallback')", name='travel_times_provider_valid'),
    sa.CheckConstraint('meters >= 0', name='travel_times_meters_nonneg'),
    sa.CheckConstraint('minutes >= 0', name='travel_times_minutes_nonneg'),
    sa.ForeignKeyConstraint(['gym_id'], ['gyms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['saved_locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id', 'gym_id')
    )
    # ### end Alembic commands ###

    # ---------------------------------------------------------------------------
    # Hand-written: four things autogenerate cannot produce.
    # ---------------------------------------------------------------------------

    # 1. The `geog` generated columns. geoalchemy2 renders the type unqualified as
    #    `geography(Point,4326)`, which does not resolve under the `search_path =
    #    public` that alembic/env.py pins on the migration connection -- Supabase
    #    installs PostGIS into `extensions`. Type and expression are both qualified
    #    here by hand. Alembic also never compares Computed() expressions, so these
    #    columns are excluded from autogenerate entirely (env.py).
    for table in ("gyms", "saved_locations"):
        op.execute(
            f"""
            alter table public.{table}
                add column geog extensions.geography(Point, 4326)
                generated always as (
                    extensions.geography(
                        extensions.st_setsrid(
                            extensions.st_makepoint(longitude, latitude), 4326))
                ) stored
            """
        )

    # 2. The GiST index behind the straight-line pre-filter. Excluded from
    #    autogenerate alongside the column it covers. `saved_locations` deliberately
    #    has none -- a user has ~3 rows and they are always fetched by user_id.
    op.execute("create index gyms_geog_idx on public.gyms using gist (geog)")

    # 3. profiles.id -> auth.users(id). Autogenerate is restricted to `public`, so it
    #    cannot see the `auth` schema and emits no foreign key for this at all.
    op.execute(
        "alter table public.profiles "
        "add constraint profiles_id_fkey foreign key (id) "
        "references auth.users (id) on delete cascade"
    )

    # 4. Row Level Security -- on, with ZERO policies, on every table. The Supabase
    #    anon key ships inside the app bundle, so PostgREST is publicly reachable
    #    whether or not we use it. FastAPI connects as the table owner and bypasses
    #    RLS, so deny-by-default costs nothing and closes that whole surface.
    #    The revokes matter separately: Supabase's default privileges grant `anon`
    #    and `authenticated` access to new tables in `public`.
    for table in TABLES:
        op.execute(f"alter table public.{table} enable row level security")
        op.execute(f"revoke all on public.{table} from anon, authenticated")


def downgrade() -> None:
    """Downgrade schema.

    Nothing hand-written to undo: dropping the tables takes the geog columns,
    gyms_geog_idx, the auth.users foreign key and the RLS state with them.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('travel_times')
    op.drop_index('saved_locations_user_idx', table_name='saved_locations')
    op.drop_index('saved_locations_one_default_idx', table_name='saved_locations', postgresql_where=sa.text('is_default'))
    op.drop_table('saved_locations')
    op.drop_table('ranking_prefs')
    op.drop_table('gym_memberships')
    op.drop_table('gym_hours')
    op.drop_table('busyness_snapshots')
    op.drop_table('busyness_curves')
    op.drop_table('profiles')
    op.drop_table('gyms')
    # ### end Alembic commands ###
