"""add gym_logos table

Logos moved out of the app bundle and into the database: the app fetches them rather than
shipping an asset catalog. Twelve rows serve sixteen gyms -- ten per-gym marks plus two
brand-level ones -- and `gyms.logo_id` records which gym uses which, replacing the old
slug-else-brand asset-catalog lookup with a foreign key. See `../boulder_bay_schema.md` 2.10.
The bytes themselves arrive in the next revision.

Two things here are hand-written rather than autogenerated:

1. The RLS enable/revoke block. Autogenerate does not emit it, and a new table does NOT
   inherit the posture of the existing nine -- Supabase's default privileges grant `anon`
   and `authenticated` access to newly created tables in `public`.
2. The foreign key's name. Autogenerate emitted `create_foreign_key(None, ...)` paired with
   `drop_constraint(None, ...)`, and the latter cannot execute. Naming it explicitly (with
   the name Postgres would have chosen anyway) makes downgrade work.

Revision ID: dba1c1f91ed2
Revises: 502a92ea0636
Create Date: 2026-09-09 11:40:37.907739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba1c1f91ed2'
down_revision: Union[str, Sequence[str], None] = '502a92ea0636'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Postgres' own default name for this constraint, spelled out so downgrade can drop it.
LOGO_FK = 'gyms_logo_id_fkey'


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gym_logos',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), server_default=sa.text("'image/png'"), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("content_type in ('image/png')", name='gym_logos_content_type_valid'),
    sa.CheckConstraint("key ~ '^[a-z0-9-]+$'", name='gym_logos_key_format'),
    sa.CheckConstraint('byte_size > 0', name='gym_logos_byte_size_positive'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.add_column('gyms', sa.Column('logo_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(LOGO_FK, 'gyms', 'gym_logos', ['logo_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Row Level Security -- on, with ZERO policies, matching every other table (see
    # 7bea7599f868). The revoke is the load-bearing half here: Supabase's default
    # privileges grant `anon` and `authenticated` access to new tables in `public`, so
    # without it this table would be readable through PostgREST with the bundled anon key.
    op.execute("alter table public.gym_logos enable row level security")
    op.execute("revoke all on public.gym_logos from anon, authenticated")


def downgrade() -> None:
    """Downgrade schema.

    The RLS state goes with the dropped table; only the foreign key needs undoing by name.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(LOGO_FK, 'gyms', type_='foreignkey')
    op.drop_column('gyms', 'logo_id')
    op.drop_table('gym_logos')
    # ### end Alembic commands ###
